name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
        cmd: install --frozen-lockfile
    - name: Lint
      uses: tinovyatkin/action-eslint@v1
      with:
        repo-token: ${{secrets.GITHUB_TOKEN}}
    - name: Typecheck
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
        cmd: typecheck
    - name: Test
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
        cmd: test
